version: "3.9"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    ports:
      - "3000:3000"